---
name: "Build"
on:
  push:
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  packages: write

jobs:
  update-base-image:
    name: Update base image
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: prompt-proto-base
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build image
        run: docker build python/base --tag $IMAGE_NAME --label "runnumber=${GITHUB_RUN_ID}"
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          [ "$VERSION" == "main" ] && VERSION=latest
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
