---
name: "Build and test service"
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/build-service.yml'
      - 'python/activator/**'
      - 'Dockerfile.activator'
  pull_request:
    paths:
      - '.github/workflows/build-service.yml'
      - 'python/activator/**'
      - 'Dockerfile.activator'
  workflow_dispatch:

permissions:
  packages: write

jobs:
  test-service:
    name: Test service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Fix permissions
        run: chmod -R a+rwX $GITHUB_WORKSPACE
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Run tests
        run: |
          docker run \
              -v $GITHUB_WORKSPACE:/home/lsst/prompt_prototype \
              ghcr.io/${{ github.repository_owner }}/prompt-proto-base:latest \
              bash -c '
                  cd /home/lsst/prompt_prototype
                  source /opt/lsst/software/stack/loadLSST.bash
                  setup -r .
                  # Fix permissions; arg must be absolute path.
                  git config --global --add safe.directory /home/lsst/prompt_prototype
                  scons'

  update-service-image:
    name: Update service image
    needs: test-service
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: prompt-proto-service
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image
        run: docker build . -f Dockerfile.activator --tag $IMAGE_NAME --label "runnumber=${GITHUB_RUN_ID}"
      - name: Push image to GitHub Container Registry
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          [ "$VERSION" == "merge" ] && VERSION=$(echo "${{ github.head_ref }}" | sed -e 's,.*/\(.*\),\1,')
          [ "$VERSION" == "main" ] && VERSION=latest
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
      - name: Login to Google Artifact Registry
        uses: docker/login-action@v2
        with:
          registry: us-central1-docker.pkg.dev
          username: _json_key_base64
          password: ${{ secrets.GAR_JSON_B64 }}
      - name: Push image to Google Artifact Registry
        run: |
          IMAGE_ID=us-central1-docker.pkg.dev/prompt-proto/prompt/$IMAGE_NAME
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          [ "$VERSION" == "merge" ] && VERSION=$(echo "${{ github.head_ref }}" | sed -e 's,.*/\(.*\),\1,')
          [ "$VERSION" == "main" ] && VERSION=latest
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
