---
name: "Build and test service"
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/build-service.yml'
      - 'python/activator/**'
      - 'Dockerfile.activator'
  pull_request:
    paths:
      - '.github/workflows/build-service.yml'
      - 'python/activator/**'
      - 'Dockerfile.activator'
  workflow_dispatch:

permissions:
  packages: write

env:
  STACK_TAG_LIST: '["latest"]'

jobs:
  matrix-gen:
    # This job exists solely because fromJSON() cannot directly accept
    # env.STACK_TAG_LIST for some reason.
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: echo "matrix=${STACK_TAG_LIST}" >> $GITHUB_OUTPUT

  test-service:
    needs: matrix-gen
    strategy:
      matrix:
        stackTag: ${{ fromJSON(needs.matrix-gen.outputs.matrix) }}
    name: Test service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Fix permissions
        run: chmod -R a+rwX $GITHUB_WORKSPACE
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Run tests
        run: |
          docker run \
              -v $GITHUB_WORKSPACE:/home/lsst/prompt_prototype \
              ghcr.io/${{ github.repository_owner }}/prompt-proto-base:${{ matrix.stackTag }} \
              bash -c '
                  cd /home/lsst/prompt_prototype
                  source /opt/lsst/software/stack/loadLSST.bash
                  setup -r .
                  # Fix permissions; arg must be absolute path.
                  git config --global --add safe.directory /home/lsst/prompt_prototype
                  scons'

  update-service-image:
    name: Update service image
    needs:
      - matrix-gen
      - test-service
    runs-on: ubuntu-latest
    strategy:
      matrix:
        stackTag: ${{ fromJSON(needs.matrix-gen.outputs.matrix) }}
    env:
      IMAGE_NAME: prompt-proto-service
      STACK_TAG: ${{ matrix.stackTag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to Google Artifact Registry
        uses: docker/login-action@v2
        with:
          registry: us-central1-docker.pkg.dev
          username: _json_key_base64
          password: ${{ secrets.GAR_JSON_B64 }}
      - name: Build image
        run: |
          docker build . -f Dockerfile.activator \
            --build-arg "STACK_TAG=$STACK_TAG" \
            --tag $IMAGE_NAME \
            --label "runnumber=${GITHUB_RUN_ID}" \
            --label "stacktag=${STACK_TAG}"
      - name: Push image to container registries
        run: |
          BRANCH=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          [ "$BRANCH" == "merge" ] && BRANCH=$(echo "${{ github.head_ref }}" | sed -e 's,.*/\(.*\),\1,')

          for IMAGE_ID in "ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME" \
                          "us-central1-docker.pkg.dev/prompt-proto/prompt/$IMAGE_NAME"; do
            if [ "$BRANCH" == "main" ]; then
              VERSION="$STACK_TAG"
            else
              VERSION="${BRANCH}-$STACK_TAG"
            fi
            echo IMAGE_ID=$IMAGE_ID
            echo VERSION=$VERSION
            docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
            docker push $IMAGE_ID:$VERSION
          done
